import type { EngineeringNode, EngineeringView } from "@epm/domain";
import { engineeringNodeName } from "./node-names.ts";
import { newId } from "./shared.ts";

export function RelationsEditor({ node, view, nodeNames, onChange }: { node: EngineeringNode; view: EngineeringView; nodeNames?: Record<string, string>; onChange: (node: EngineeringNode) => void }) {
  const others = view.document.nodes.filter(item => item.id !== node.id && item.status !== "archived");
  const prerequisites = node.prerequisites ?? [], interactions = node.interactions ?? [];
  const update = (patch: Partial<EngineeringNode>) => onChange({ ...node, ...patch });
  return <div data-edit-target="relations">
    <section className="eng-section"><div className="eng-section-heading"><h2>开始前需要完成什么</h2><button type="button" onClick={() => update({ prerequisites: [...prerequisites, { id: newId("prerequisite"), node_id: "", reason: "" }] })}>添加开工前提</button></div><p className="eng-muted">只填写确实必须等待的前提。已声明的成果输入会按交接规则等待，无需重复添加。</p>{prerequisites.map((item, index) => <div className="eng-edit-item" key={item.id} data-edit-target={`prerequisite:${item.id}`}><div className="eng-item-heading"><strong>前提 {index + 1}</strong><button type="button" onClick={() => update({ prerequisites: prerequisites.filter(row => row.id !== item.id) })}>删除前提</button></div><label>等待哪项完成<select value={item.node_id} onChange={event => update({ prerequisites: prerequisites.map(row => row.id === item.id ? { ...row, node_id: event.target.value } : row) })}><option value="">选择项目成果…</option>{others.map(other => <option key={other.id} value={other.id}>{engineeringNodeName(other, nodeNames)}</option>)}</select></label><label>为什么必须等待<textarea rows={2} value={item.reason} onChange={event => update({ prerequisites: prerequisites.map(row => row.id === item.id ? { ...row, reason: event.target.value } : row) })} /></label></div>)}</section>
    <section className="eng-section"><div className="eng-section-heading"><h2>使用时怎样配合</h2><button type="button" onClick={() => update({ interactions: [...interactions, { id: newId("interaction"), target_node_id: "", source_output_id: "", target_input_id: "", purpose: "", scenario: "" }] })}>添加使用联系</button></div><p className="eng-muted">说明建成后的功能如何配合。可以双向联系；这里的连线不自动让建设任务互相等待。</p>{interactions.map((item, index) => { const target = others.find(other => other.id === item.target_node_id); return <div className="eng-edit-item" key={item.id} data-edit-target={`interaction:${item.id}`}><div className="eng-item-heading"><strong>使用联系 {index + 1}</strong><button type="button" onClick={() => update({ interactions: interactions.filter(row => row.id !== item.id) })}>删除使用联系</button></div><label>与谁配合<select value={item.target_node_id} onChange={event => update({ interactions: interactions.map(row => row.id === item.id ? { ...row, target_node_id: event.target.value, target_input_id: "" } : row) })}><option value="">选择配合的部分…</option>{others.map(other => <option key={other.id} value={other.id}>{engineeringNodeName(other, nodeNames)}</option>)}</select></label><label>这条联系有什么用<textarea rows={2} value={item.purpose} onChange={event => update({ interactions: interactions.map(row => row.id === item.id ? { ...row, purpose: event.target.value } : row) })} /></label><label>怎样验证实际配合<textarea rows={2} value={item.scenario} onChange={event => update({ interactions: interactions.map(row => row.id === item.id ? { ...row, scenario: event.target.value } : row) })} /></label><details className="eng-disclosure"><summary>具体交接位置（可选）</summary><label>本项提供的成果<select value={item.source_output_id} onChange={event => update({ interactions: interactions.map(row => row.id === item.id ? { ...row, source_output_id: event.target.value } : row) })}><option value="">未指定具体成果</option>{node.delivery?.outputs.map(output => <option value={output.id} key={output.id}>{output.title}</option>)}</select></label><label>接收方的输入<select value={item.target_input_id} onChange={event => update({ interactions: interactions.map(row => row.id === item.id ? { ...row, target_input_id: event.target.value } : row) })}><option value="">未指定具体输入</option>{target?.delivery?.inputs.map(input => <option value={input.id} key={input.id}>{input.title}</option>)}</select></label></details></div>; })}</section>
  </div>;
}
