import { useEffect, useState } from "react";
import type { EngineeringNode, EngineeringRun, EngineeringView } from "@epm/domain";
import type { EngineeringApi } from "../../engineering-api.ts";
import { actionNames, criterionNames, runStatusLabel, timeLabel } from "./shared.ts";

import { HandoffPanel } from "./HandoffPanel.tsx";
import { SourceProofPanel } from "./SourceProofPanel.tsx";
import { FrozenDeliveryContract } from "./FrozenDeliveryContract.tsx";

interface Props { onDraftContentChange?: (content: string) => void; onDraftDirtyChange?: (dirty: boolean) => void; api: EngineeringApi; node: EngineeringNode; view: EngineeringView; busy: boolean; onMutation: (operation: () => Promise<EngineeringView>, message: string) => Promise<boolean>; onSelect: (id: string) => void }
export function RunPanel({ api, node, view, busy, onMutation, onSelect, onDraftDirtyChange, onDraftContentChange }: Props) {
  const runs = view.document.runs.filter((item) => item.node_id === node.id).slice().reverse();
  const [selectedRun, setSelectedRun] = useState("");
  const run = runs.find((item) => item.id === selectedRun) ?? runs[0];
  const [checks, setChecks] = useState<Record<string, boolean>>({});
  const [checkNotes, setCheckNotes] = useState<Record<string, string>>({});
  const [note, setNote] = useState("");
  const [feedback, setFeedback] = useState<Record<string, string>>({});
  useEffect(() => { setChecks({}); setCheckNotes({}); setNote(""); }, [run?.id]);
  const uses = view.document.capability_uses.filter((item) => item.run_id === run?.id);
  const isLatest = run?.id === view.derived[node.id]?.latest_run_id;
  const canReview = isLatest && run?.status === "review";
  const unsubmitted = !!((canReview && (note.trim() || Object.keys(checks).length || Object.values(checkNotes).some(value => value.trim()))) || uses.some((use) => use.state !== "feedback_recorded" && feedback[use.id]?.trim()));
  const unsubmittedText = [canReview && note.trim() ? `验收意见：${note}` : "", ...(canReview ? run.snapshot.node.criteria.filter(criterion => Object.hasOwn(checks, criterion.id) || checkNotes[criterion.id]?.trim()).map(criterion => `${criterion.text}：${checks[criterion.id] === true ? "通过" : checks[criterion.id] === false ? "未通过" : "尚未核对"}${checkNotes[criterion.id]?.trim() ? `；${checkNotes[criterion.id]}` : ""}`) : []), ...uses.filter((use) => use.state !== "feedback_recorded" && feedback[use.id]?.trim()).map((use) => `能力反馈（${use.summary || use.capability_id}）：${feedback[use.id]}`)].filter(Boolean).join("\n\n");
  useEffect(() => { onDraftContentChange?.(unsubmittedText); }, [unsubmittedText, onDraftContentChange]);
  useEffect(() => () => onDraftContentChange?.(""), [onDraftContentChange]);
  useEffect(() => { onDraftDirtyChange?.(unsubmitted); }, [unsubmitted, onDraftDirtyChange]);
  useEffect(() => () => onDraftDirtyChange?.(false), [onDraftDirtyChange]);
  async function review(verdict: "accepted" | "needs_revision") {
    if (!run) return;
    await onMutation(() => api.review(run.id, verdict, note, run.snapshot.node.criteria.filter((criterion) => criterion.kind === "manual" && Object.hasOwn(checks, criterion.id)).map((criterion) => ({ criterion_id: criterion.id, passed: checks[criterion.id], note: checkNotes[criterion.id]?.trim() ?? "" }))), verdict === "accepted" ? "已提交验收结果" : "已退回修改");
  }
  return <div className="eng-run-panel">
    <section className="eng-section"><div className="eng-section-heading"><h2>运行与证据</h2>{runs.length > 0 && <select aria-label="选择历史运行" value={run?.id ?? ""} onChange={(event) => setSelectedRun(event.target.value)}>{runs.map((item, index) => <option key={item.id} value={item.id}>{index === 0 ? "最近一次" : `历史 ${runs.length - index}`} · {timeLabel(item.started_at)} · {runStatusLabel(item)}</option>)}</select>}</div>
      {!run && <div className="eng-empty-state"><strong>计划尚未执行</strong><p>先完善方案与验收条件，检查就绪后加入执行队列。每次执行会保留当时的方案和证据。</p></div>}
      {run && <><div className="eng-run-summary"><span className={`eng-status is-${run.status}`}>{runStatusLabel(run)}</span><span>{run.mode === "integration" ? "整合检查" : run.mode === "external" ? "协作逐步执行" : "受控执行"}</span><time>{timeLabel(run.started_at)}</time></div>{!isLatest && <p className="eng-notice">正在查看历史运行。历史证据保留供追溯，不能用于当前版本验收。</p>}{run.reason && <p className="eng-notice">{run.reason}</p>}{run.status === "stale" && <p className="eng-notice">该次运行对应的方案已变更，需要按当前方案重新执行。</p>}
        <ol className="eng-action-timeline">{run.snapshot.node.actions.map((action, index) => { const completed = run.completed_action_ids.includes(action.id); const current = run.current_action === action.id; return <li key={action.id} className={completed ? "is-done" : current ? "is-current" : ""}><span className="eng-action-dot">{completed ? "✓" : index + 1}</span><div><strong>{action.title}</strong><small>{actionNames[action.type]} · {completed ? "已执行" : current ? "正在执行" : "等待执行"}</small></div>{action.type === "agent_artifact" && !completed && <small className="eng-agent-wait">等待负责人提交产出</small>}</li>; })}</ol>
        {run.snapshot.children.length > 0 && <div className="eng-integrated-children"><h3>本次整合的子任务</h3>{run.snapshot.children.map((child) => <button type="button" className="eng-text-button" key={child.node_id} onClick={() => onSelect(child.node_id)}>{view.document.nodes.find((item) => item.id === child.node_id)?.title ?? child.node_id} ↗</button>)}</div>}
      </>}
    </section>
    {run?.mode === "external" && <HandoffPanel api={api} run={run} revision={view.document.revision} />}
    {run && <SourceProofPanel run={run} />}
    {run && <>
      <section className="eng-section"><h2>逐项验收</h2><p className="eng-muted">核对本次运行冻结的条件与实际证据。执行结束不代表验收通过。</p>{run.snapshot.node.criteria.map((criterion) => { const evidence = run.evidence.filter((item) => item.criterion_id === criterion.id); const automaticPassed = evidence.some((item) => item.passed === true) && !evidence.some((item) => item.passed === false); return <div className="eng-review-item" key={criterion.id}><div className="eng-section-heading"><h3>{criterion.text}</h3><span className="eng-muted">{criterionNames[criterion.kind]}</span></div>{criterion.kind === "manual" && canReview ? <div className="eng-criterion-verdict"><label className="eng-check-row"><input type="checkbox" checked={checks[criterion.id] === true} disabled={busy} onChange={(event) => setChecks((current) => { const next = { ...current }; if (event.target.checked) next[criterion.id] = true; else delete next[criterion.id]; return next; })} /><span>我已核对，满足此条件</span></label><button type="button" className="eng-text-button" aria-pressed={checks[criterion.id] === false} disabled={busy} onClick={() => setChecks(current => { const next = { ...current }; if (next[criterion.id] === false) delete next[criterion.id]; else next[criterion.id] = false; return next; })}>{checks[criterion.id] === false ? "本条未通过 · 撤销标记" : "标记本条未通过"}</button><label>本条核对意见<textarea rows={2} aria-label={`核对意见：${criterion.text}`} value={checkNotes[criterion.id] ?? ""} disabled={busy} placeholder="记录这条条件的实际结果或需要修复的地方。" onChange={event => setCheckNotes(current => ({ ...current, [criterion.id]: event.target.value }))} /></label><small>{Object.hasOwn(checks, criterion.id) ? checks[criterion.id] ? "本条已核对通过，尚未提交" : "本条未通过，尚未提交" : "本条尚未核对"}</small></div> : <p className={automaticPassed ? "eng-success-text" : "eng-muted"}>{automaticPassed ? "核对通过" : evidence.some((item) => item.passed === false) ? "核对未通过" : "尚无通过证据"}</p>}{evidence.map((item) => <Evidence key={item.id} item={item} run={run} api={api} />)}{evidence.length === 0 && <p className="eng-empty-inline">还没有关联证据。</p>}</div>; })}
        {canReview && <div className="eng-review-form"><label>验收意见<textarea rows={3} value={note} disabled={busy} onChange={(event) => setNote(event.target.value)} placeholder="记录核对结果，或说明需要修改的地方。" /></label><div className="eng-inline-actions"><button type="button" className="eng-primary" disabled={busy || !note.trim() || run.snapshot.node.criteria.some((criterion) => criterion.kind === "manual" && !checks[criterion.id])} onClick={() => void review("accepted")}>确认验收通过</button><button type="button" disabled={busy || !note.trim()} onClick={() => void review("needs_revision")}>退回修改</button></div></div>}{run.review_note && <blockquote className="eng-review-note">{run.review_note}<small>{timeLabel(run.reviewed_at)}</small></blockquote>}
      </section>
      <section className="eng-section"><h2>本次产出</h2>{run.evidence.filter((item) => !item.criterion_id || item.kind === "artifact" || item.kind === "capability").map((item) => <Evidence key={item.id} item={item} run={run} api={api} />)}{run.evidence.length === 0 && <p className="eng-empty-inline">尚未生成可查看的执行证据。</p>}<details className="eng-disclosure"><summary>查看运行身份与冻结方案</summary><dl className="eng-summary-list"><div><dt>执行人</dt><dd>{run.actor}</dd></div><div><dt>运行编号</dt><dd>{run.id}</dd></div><div><dt>方案版本</dt><dd>{run.snapshot.node.revision}</dd></div><div><dt>{run.status === "queued" ? "登记时间" : "开始时间"}</dt><dd>{timeLabel(run.started_at)}</dd></div><div><dt>结束时间</dt><dd>{timeLabel(run.finished_at)}</dd></div><div><dt>执行思路</dt><dd className="eng-preserve">{run.snapshot.node.method || "未填写"}</dd></div></dl><FrozenDeliveryContract nodeId={run.snapshot.node.id} delivery={run.snapshot.node.delivery} criteria={run.snapshot.node.criteria} lineage={run.snapshot.delivery_lineage} /></details></section>
      {uses.length > 0 && <section className="eng-section"><h2>能力应用与反馈</h2>{uses.map((use) => <div className="eng-capability-row" key={use.id}><h3>{use.summary || use.capability_id}</h3><p className="eng-muted">{use.state === "prepared" ? "已准备应用包，尚未使用" : use.state === "used" ? "已实际应用" : "反馈已记录"} · 版本 {use.version}</p><p>{use.evidence_ids.length} 条关联证据</p>{!["accepted", "rejected"].includes(run.status) && <p className="eng-muted">完成本次验收后，可以提交应用反馈。</p>}{use.state !== "feedback_recorded" && <><label>这次应用有什么帮助或不足<textarea rows={2} disabled={busy || !["accepted", "rejected"].includes(run.status) || use.state === "prepared"} value={feedback[use.id] ?? ""} onChange={(event) => setFeedback((current) => ({ ...current, [use.id]: event.target.value }))} /></label><button type="button" disabled={busy || !["accepted", "rejected"].includes(run.status) || use.state === "prepared" || !feedback[use.id]?.trim()} onClick={() => void onMutation(() => api.feedback(run.id, use.id, feedback[use.id]), "能力反馈已写入来源记录")}>提交应用反馈</button></>}{use.feedback_receipt && <p className="eng-success-text">已保留反馈回执</p>}<details className="eng-disclosure"><summary>来源与证据校验</summary><p className="eng-wrap">能力：{use.capability_id}</p><p className="eng-wrap">应用包校验值：{use.packet_hash}</p></details></div>)}</section>}
    </>}
  </div>;
}

function Evidence({ item, run, api }: { api: EngineeringApi; item: EngineeringRun["evidence"][number]; run: EngineeringRun }) {
  return <div className="eng-evidence"><span className={item.passed === false ? "eng-error-mark" : "eng-evidence-mark"}>{item.passed === false ? "×" : item.passed === true ? "✓" : "↳"}</span><div><p>{item.summary}</p>{item.path && <a href={api.artifact(run.id, item.path)} target="_blank" rel="noreferrer">查看实际文件 ↗</a>}{item.sha256 && <details><summary>文件校验值</summary><code className="eng-wrap">{item.sha256}</code></details>}<small>{timeLabel(item.created_at)}</small></div></div>;
}
